### ISSUE TITLE
Let's finish the exercise!!!

### ISSUE THREAD

**Issue by oneeyedman** [esterlegaz/e-s2-evaluacion-intermedia-esterlegaz#1]
Good job @esterlegaz !!!

Here you have some tips to improve the exercise:

- [x] Define a good structure of folders and files for the project
- [x] Connect the label to the input using the `for` attribute of the label and the `id` of the input
- [x] Use a `label` to define the content of the input
- [x] Refine the logic to generate and save the random number (remember we gave you a sample code)
- [x] Define the logic to make the counter work, a good old constant will suffice ;)
- [ ] Remember that you can't reassign the value of a constant variable
- [ ] Extract the feedback painter to a function
- [x] Move variables declaration to the top of the file
- [x] Use ONE `addEventListener` for each event. If you need to execute multiple functions at once perhaps you can create a new function and call inside every function you may need

You are close to the exercise solution, but here you are a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables
2. Generate the random number and save it to a variable
3. Init counter of trials to 0
4. Define a function that executes when the user clicks on the button, that
  - increments the counter and paints its value in the HTML
  - collect the value of the HTML input and compare it with the random number
    - if they are equal, draw a 'You Win' message
    - if it's lower, draw a 'Too short' message
    - if it's higher, draw a 'Too long' message
5. Assign a listener to the button click to execute the previous function

Let me know if you have any doubts ;)

Go for it!!

**Comment by oneeyedman** [comment]
Well done @esterlegaz!

Merge Dev branch to Master when you are ready!

**Comment by esterlegaz** [comment]
Perfect! I'm gonna merge it.
Thanks :)
